// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2130.Robot2016;
    

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.*;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveLeftMotor;
    public static SpeedController driveRightMotor;
    public static RobotDrive driveRobotControl;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftMotor = new Talon(0);
        LiveWindow.addActuator("Drive", "LeftMotor", (Talon) driveLeftMotor);
        
        driveRightMotor = new Talon(1);
        LiveWindow.addActuator("Drive", "RightMotor", (Talon) driveRightMotor);
        
        driveRobotControl = new RobotDrive(driveLeftMotor, driveRightMotor);
        
        driveRobotControl.setSafetyEnabled(true);
        driveRobotControl.setExpiration(0.1);
        driveRobotControl.setSensitivity(0.5);
        driveRobotControl.setMaxOutput(1.0);
        


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
